config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'

  resources :business_assets do
    collection do
      get 'search/', :action => 'search', :as => 'search'
    end
  end

  get 'dashboard', to: "business_assets#dashboard", as: :dashboard
  get '/transactions/:id/compare', to: 'transactions#compare', as: 'compare'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/business_asset.rb
class BusinessAsset < ApplicationRecord
  belongs_to :user
  belongs_to :geographical_location

  has_many :transactions
  has_one :last_transaction, -> { order("date DESC") }, class_name: "Transaction"

  has_many :rentals
  has_many :attachments, dependent: :destroy
  has_many :asset_categories, through: :business_asset_categories
  belongs_to :business_asset_manager, class_name: "Company", optional: true
  accepts_nested_attributes_for :geographical_location
  BUSINESS_ASSET_TYPES = ["Stock warehouse", "Logistics warehouse", "Shop", "Office"]


  def current_rental
    unless self.rentals.empty?
      self.rentals.select { |r| !r.end_date || (r.start_date <= Date.today && Date.today <= r.end_date) }.first
    else
      nil
    end
  end

  def current_transaction
    unless self.transactions.empty?
      self.transactions.select {|r| r.date <= Date.today }.sort { |r| r.date }.last
    else
      nil
    end
  end

  def owner
    unless self.transactions.empty?
      self.transactions.select {|r| r.date <= Date.today }.sort { |r| r.date }.last.buyer
    else
      nil
    end
  end

  def seller
    unless self.transactions.empty?
      self.transactions.select {|r| r.date <= Date.today }.sort { |r| r.date }.last.seller
    else
      nil
    end
  end

  def tenant
    unless self.rentals.empty?
      self.rentals.select { |r| !r.end_date || (r.start_date <= Date.today && Date.today <= r.end_date) }.first.tenant
    else
      nil
    end
  end


  def define_attributes(my_hash, user)
    address = my_hash['geographical_location']['address'] if !my_hash['geographical_location']['address'].empty?
    geographical_location = GeographicalLocation.find_by(
      address: address)

    if geographical_location.nil? && !address.nil?
      geographical_location = GeographicalLocation.new(address: address)
      geographical_location.save!
    end

    asset_manager_name = my_hash['company']['name'] if !my_hash['company']['name'].empty?
    asset_manager = Company.find_by(name: asset_manager_name)
    if asset_manager.nil? && !asset_manager_name.nil?
      asset_manager = Company.new(name: asset_manager_name)
      asset_manager.save!
    end




    self.user = user
    self.geographical_location = geographical_location
    self.business_asset_manager = asset_manager
    self.surface = my_hash['surface'].gsub(/[^\d^\.]/, '').to_f if !my_hash['surface'].empty?
    self.land_surface = my_hash['land_surface'] if !my_hash['land_surface'].empty?
    self.construction_year = my_hash['construction_year'] if !my_hash['construction_year'].empty?
    self.height = my_hash['height'] if !my_hash['height'].empty?
    self.occupancy_rate = my_hash['occupancy_rate'] if !my_hash['occupancy_rate'].empty?
    self.office_area_share = my_hash['office_area_share'] if !my_hash['office_area_share'].empty?
    self.potential_annual_rent = my_hash['potential_annual_rent'].gsub(/[^\d^\.]/, '').to_f if !my_hash['potential_annual_rent'].empty?
    self.potential_annual_rent_sqm = compute_sqm_rent(self.potential_annual_rent, self.surface)

  end

  private

  def compute_sqm_rent(rent, surface)
    unless rent.nil? || surface.nil? || surface.zero?
      rent / surface
    else
      nil
    end
  end
end

app/controllers/business_assets_controller.rb
class BusinessAssetsController < ApplicationController
  before_action :set_business_asset, only: [:show, :edit, :update, :destroy]
  skip_after_action :verify_authorized, only:  [:search, :destroy]

def search
    @business_assets = policy_scope(BusinessAsset)
    .joins(:geographical_location)
      my_hash = params["search"]
      categories_array = [params['post']['category_ids'].map {|cat| cat.to_i}.drop(1)].flatten
      .map{|cat| AssetCategory.find(cat).name}

      price_array = params["post"]["price_range"][0].split(',').map{|x| x.to_i}
      if !my_hash["address"].empty?
        sql_query = " \
        geographical_locations.address ILIKE :query \
        "
        @business_assets = @business_assets
        .where(sql_query, query: "%#{my_hash["address"] }%")

      end

      unless categories_array.empty?
        @business_assets = @business_assets.where(asset_type: categories_array)
      end

      unless price_array.empty?
        @business_assets = @business_assets.select do |x|
          if x.last_transaction == nil
            false
          else
            x.last_transaction.price >= price_array[0] && x.last_transaction.price <= price_array[1]
          end
        end
      end



    @markers = @business_assets.map do |business_asset|
      # next if business_asset.geographical_location.longitude.nil? || business_asset.geographical_location.latitude.nil?
      {
        title: business_asset.geographical_location.address,
        lng: business_asset.geographical_location.longitude,
        lat: business_asset.geographical_location.latitude,
        icon: ActionController::Base.helpers.image_path("#{business_asset.asset_type.downcase.delete(' ')}.png")
      }
    end
    @markers.select! { |x| !x.nil? }
    respond_to do |format|
      format.js
    end

end

  def index
    if params[:query].present?
      sql_query = " \
      geographical_locations.address ILIKE :query \
      "
      @business_assets = policy_scope(BusinessAsset).joins(:geographical_location).where(
      sql_query, query: "%#{params[:query]}%")
      @markers = @business_assets.map do |business_asset|
        # next if business_asset.geographical_location.longitude.nil? || business_asset.geographical_location.latitude.nil?
        {
          title: business_asset.geographical_location.address,
          lng: business_asset.geographical_location.longitude,
          lat: business_asset.geographical_location.latitude,
          infoWindow: {content: render_to_string(partial: "/business_assets/infowindow", locals: { business_asset: business_asset })},
          icon: ActionController::Base.helpers.image_path("#{business_asset.asset_type.downcase.delete(' ')}.png")
        }
      end
    else
        @business_assets = policy_scope(BusinessAsset).order(created_at: :desc).limit(51)
        @markers = @business_assets.map do |business_asset|
          next if business_asset.geographical_location.longitude.nil? || business_asset.geographical_location.latitude.nil?
          {
            title: business_asset.geographical_location.address,
            lng: business_asset.geographical_location.longitude,
            lat: business_asset.geographical_location.latitude,
            infoWindow: {content: render_to_string(partial: "/business_assets/infowindow", locals: { business_asset: business_asset })},
            icon: ActionController::Base.helpers.image_path("#{business_asset.asset_type.downcase.delete(' ')}.png")
          }
        end
        @markers.select! { |x| !x.nil? }
        @business_assets
    end
    authorize @business_assets
    render layout: 'application_new'
  end

  def show
    @markers =
      [{
        title: @business_asset.geographical_location.address,
        lng: @business_asset.geographical_location.longitude,
        lat: @business_asset.geographical_location.latitude,
        infoWindow: {content: render_to_string(partial: "/business_assets/infowindow", locals: { business_asset: @business_asset })},
        icon: ActionController::Base.helpers.image_path("#{@business_asset.asset_type.downcase.delete(' ')}.png")
      }]
    ap @business_asset.attachments
    @carroussel = @business_asset.attachments.sort_by { |file| file.id }
    ap @carroussel
    render layout: 'application_new'
  end

  def new
    @business_asset = BusinessAsset.new
    authorize @business_asset
    render layout: 'application_new'
  end

  def create
    my_hash = params['search']
    categories_array = [params['post']['category_ids'].map {|cat| cat.to_i}.drop(1)].flatten
    business_asset = BusinessAsset.new
    business_asset.define_attributes(my_hash,current_user)


    if business_asset.valid?
      business_asset.asset_type = AssetCategory.find(categories_array.first.to_i).name if !categories_array.empty?
      business_asset.save!
      categories_array.each do |cat|
        asset_category = AssetCategory.find(cat)
        BusinessAssetCategory.create(business_asset: business_asset, asset_category: asset_category)
      end
      # add a default picture that's the street view screenshot
      a = Attachment.new
      a.business_asset = business_asset
      a.attachment_type = 'photo'
      loc = business_asset.geographical_location
      url = "https://maps.googleapis.com/maps/api/streetview?size=400x400&location=#{loc.latitude},#{loc.longitude}&fov=90&heading=235&pitch=10&key=#{ENV['GOOGLE_API_BROWSER_KEY']}"
      a.url = url
      a.remote_file_url = url
      a.save!

    else
      flash[:alert] = business_asset.errors.full_messages
      render :new
    end

    rental = Rental.new
    rental.define_attributes(my_hash['rentals'], business_asset)
    if rental.valid?
      rental.save!
    elsif nil_attributes?(rental) == false
      flash[:alert] = rental.errors.full_messages
      render :new
    end

    transaction = Transaction.new
    transaction.define_attributes(my_hash['transactions'], business_asset)
    if transaction.valid?
        transaction.save!
    elsif nil_attributes?(transaction) == false
      flash[:alert] = transaction.errors.full_messages
      render :new
    end
    if business_asset.valid?
      redirect_to business_asset_path(business_asset)
    end

    attachment = Attachment.new(business_asset: business_asset)
    if my_hash[:attachment]
      file = my_hash[:attachment][:file]
      attachment.file = file
      attachment.save
    end

    authorize business_asset
  end

  # redirect_to business_assets_path


  def edit
  end

  def update
  end

  def destroy
    respond_to do |format|
    format.html
    format.js
    end
    # @business_asset = BusinessAsset.find(params[:id])
    @business_asset.destroy
    redirect_to business_assets_path
  end

  def dashboard
    authorize policy_scope(BusinessAsset)
    @buyers_unique = Company.joins(:bought_transactions).select(:name).distinct
    if params[:option].present?
      @buyer = Company.find_by(name: params[:option])
    else
      @buyer = Company.find_by(name: "VLD")
    end
    last_transactions = BusinessAsset.all.map { |business_asset| business_asset.last_transaction }
    buyer_last_transactions = last_transactions.select { |transaction| transaction.buyer == @buyer }
    @business_assets = buyer_last_transactions.map { |buyer_last_transaction| buyer_last_transaction.business_asset }
                                              .sort_by {|b| b.rentals.last.annual_rent }
                                              .reverse
    @max_price = @business_assets.map { |bus| bus.transactions.last.price }.max()
    @markers = @business_assets.map do |business_asset|
        next if business_asset.geographical_location.longitude.nil? || business_asset.geographical_location.latitude.nil?
        {
          title: business_asset.geographical_location.address,
          lng: business_asset.geographical_location.longitude,
          lat: business_asset.geographical_location.latitude,
          infoWindow: {content: render_to_string(partial: "/business_assets/infowindow", locals: { business_asset: business_asset })},
          icon: ActionController::Base.helpers.image_path("#{business_asset.asset_type.downcase.delete(' ')}.png")
        }
      end
    render layout: 'application_demo'
  end

private

  def set_business_asset
    @business_asset = policy_scope(BusinessAsset).find(params[:id])
    authorize @business_asset
  end

  def nil_attributes? (class_instance)
    class_instance.attributes.values.select {|x| !x.nil? || x.nil? ? false : x.positive?}.empty?
  end
end

app/views/business_assets/forms/_add_attachment.html.erb
<div class="row row-form">
  <div class="col-xs-8 col-xs-offset-2">
    <h3 class="form-section">Add attachment ?</h3>
       <%= f.fields_for :attachments do |att| %>
        <%= att.input :attachment_type, label: false %>
        <%= att.input :file %>
        <%= att.input :file_cache, as: :hidden %>
      <% end %>
    </div>
    <div class="btn-section">
      <%= f.submit "add an asset", class: "btn btn-primary btn-form" %>
    </div>
</div>

app/views/business_assets/forms/_address.html.erb
<h3 class="form-section">Where is the asset ?</h3>
  <%= f.fields_for :geographical_location do |loc| %>
    <%= loc.input :address, label: false, input_html: {id: 'asset_address', placeholder: "Enter an address"} %>
  <% end %>
  <div
    id="map"
    data-markers=""
  ></div>

app/views/business_assets/forms/_asset_type.html.erb
    <h3 class="form-section">What kind of asset is it ?</h3>
    <div class="form-group">
      <input type="hidden" name="post[category_ids][]" value="">
      <div class="category-choices">
        <% AssetCategory.all.sort_by {|x| x.name}.each do |category| %>
            <input type="checkbox" class="category-choice hidden" value="<%= category.id %>" name="post[category_ids][]" id="post_category_ids_<%= category.id %>">
            <label for="post_category_ids_<%= category.id %>" class="category-choice">
              <div class="category-name">
                <%= category.name %>
              </div>
              <i class="<%= category.pictogram %>"></i>
            </label>
        <% end %>
       </div>
    </div>

app/views/business_assets/forms/_attachements.html.erb
<h3 class="form-section">Add attachments ?</h3>

<%= f.fields_for :attachment do |att| %>
  <%= att.file_field :file %>
<% end %>

  <div class="btn-section">
    <%= f.submit "add an asset", class: "btn btn-primary btn-form" %>
  </div>

app/views/business_assets/forms/_financial_information.html.erb
  <h3  class="form-section">Transactions</h3>
  <%= f.fields_for :transactions do |tr| %>
    <div class="form-input-title">Price</div>
    <div class="input-group mb-2 mr-sm-2 mb-sm-0">
      <div class="input-group-addon">€</div>
      <%= tr.input :price, as: :string, label: false, input_html: {class: 'form-input-numeric'} %>
    </div>

      <div class="form-input-title">Buyer</div>
      <div class="input-group mb-2 mr-sm-2 mb-sm-0">
        <%= tr.input :buyer_name, as: :string, label: false %>
      </div>
      <div class="form-input-title">Seller</div>
      <div class="input-group mb-2 mr-sm-2 mb-sm-0">
        <%= tr.input :seller_name, as: :string, label: false %>
      </div>


      <div class="form-input-title">Date</div>
      <div class="input-group mb-2 mr-sm-2 mb-sm-0">
        <%= tr.input :date, as: :string, label:false, input_html: {class: "datepicker"} %>
      </div>

  <% end %>

    <h3 class="form-section">Rentals</h3>
      <%= f.fields_for :rentals do |re| %>
          <div class="form-input-title">Annual rent</div>
          <div class="input-group mb-2 mr-sm-2 mb-sm-0">
            <div class="input-group-addon">€</div>
            <%= re.input :annual_rent, as: :string, label: false, input_html: {class: 'form-input-numeric'} %>
          </div>
          <div class="form-input-title">Tenant</div>
          <div class="input-group mb-2 mr-sm-2 mb-sm-0">
            <%= re.input :tenant_name, as: :string, label: false %>
          </div>

          <div class="form-input-title">Start date</div>
          <div class="input-group mb-2 mr-sm-2 mb-sm-0">
            <%= re.input :start_date, as: :string, label:false, input_html: {class: "datepicker"} %>
          </div>
          <div class="form-input-radio">
            <div class="input-group mb-2 mr-sm-2 mb-sm-0">
            <%= re.input :break_dates, as: :radio_buttons, collection: [['0', '3 - 6 - 9 '], ['1', 'other']], label_method: :second, value_method: :first %>

            </div>
          </div>

          <div class="break-dates" hidden>
            <div class="form-input-title">Break date 1</div>
            <%= re.input :break_date_1, as: :string, label:false, input_html: {class: "datepicker"} %>
            <div class="form-input-title">Break date 2</div>
            <%= re.input :break_date_2, as: :string, label:false, input_html: {class: "datepicker"} %>
            <div class="form-input-title">Break date 3</div>
            <%= re.input :break_date_3, as: :string, label:false, input_html: {class: "datepicker"} %>
          </div>
      <% end %>

    <h3 class="form-section">Business data</h3>
    <div class="form-input-title">Potential annual rent</div>
    <div class="input-group mb-2 mr-sm-2 mb-sm-0">
      <div class="input-group-addon">€</div>
      <%= f.input :potential_annual_rent, as: :string, label: false, input_html: {class: 'form-input-numeric'} %>
    </div>

app/views/business_assets/forms/_form.html.erb
<div class="col-xs-12 col-sm-8 col-sm-offset-2">
  <div class="steps">
    <div class="step">
      <i class="fas fa-location-arrow step-logo"></i>
      <p class="step-title">Location</p>
    </div>
    <div class="step">
      <i class="fas fa-cog step-logo"></i>
      <p class="step-title">Type</p>
    </div>
    <div class="step">
      <i class="fas fa-info-circle step-logo"></i>
      <p class="step-title">Information</p>
    </div>
    <div class="step">
      <i class="fas fa-dollar-sign step-logo"></i>
      <p class="step-title">Financials</p>
    </div>
     <div class="step">
      <i class="fas fa-paperclip step-logo"></i>
      <p class="step-title">Attachements</p>
    </div>
  </div>

  <%= simple_form_for :search, url: business_assets_path, method: :post do |f| %>
  <div class="row-form">
    <button type="button" id="prevBtn" class="nav-btn"> < </button>
    <div class="col-xs-10 col-xs-offset-1">
      <div class="tab-content">
          <div id="form-tab-1" class="tab">
              <%= render 'business_assets/forms/address', f:f   %>
          </div>
          <div id="form-tab-2" class="tab">
              <%= render 'business_assets/forms/asset_type', f:f   %>
          </div>
          <div id="form-tab-3" class="tab">
              <%= render 'business_assets/forms/general_information', f:f   %>
          </div>
          <div id="form-tab-4" class="tab">
              <%= render 'business_assets/forms/financial_information', f:f   %>
          </div>
          <div id="form-tab-5" class="tab">
              <%= render 'business_assets/forms/attachements', f:f   %>
          </div>
      </div>
      <% end %>
    </div>
    <button type="button" id="nextBtn" class="nav-btn"> > </button>
  </div>
</div>

app/views/business_assets/forms/_general_information.html.erb
    <h3 class="form-section">Asset information</h3>
      <div class="form-input-title">Surface</div>
      <div class="input-group mb-2 mr-sm-2 mb-sm-0">
        <div class="input-group-addon">m²</div>
        <%= f.input :surface, as: :string, label: false, input_html: {class: 'form-input-numeric'} %>
      </div>

      <div class="form-input-title">Land surface</div>
      <div class="input-group mb-2 mr-sm-2 mb-sm-0">
        <div class="input-group-addon">m²</div>
        <%= f.input :land_surface, as: :string, label: false, input_html: {class: 'form-input-numeric'} %>
      </div>

      <div class="form-input-title">Construction year</div>
      <div class="input-group mb-2 mr-sm-2 mb-sm-0">
        <%= f.input :construction_year, as: :integer, collection: 1900..2020, label:false %>
      </div>

      <div class="form-input-title">Height</div>
      <div class="input-group mb-2 mr-sm-2 mb-sm-0">
        <%= f.input :height, as: :integer, collection: 1900..2020, label:false %>
      </div>

      <div class="input-group mb-2 mr-sm-2 mb-sm-0">
        <div class="form-input-checkbox">
          <%= f.input :has_icpe, as: :boolean, checked_value: true, unchecked_value: false, input_html: {class: 'form-input-checkbox'}%>
        </div>
      </div>

    <h3 class="form-section">Occupancy information</h3>
      <div class="form-input-title">Occupancy rate</div>
      <div class="input-group mb-2 mr-sm-2 mb-sm-0">
        <div class="input-group-addon">%</div>
        <%= f.input :occupancy_rate, as: :float, label: false, input_html: {class: 'form-input-numeric'} %>
      </div>

      <div class="form-input-title">Office area share</div>
      <div class="input-group mb-2 mr-sm-2 mb-sm-0">
        <div class="input-group-addon">%</div>
        <%= f.input :office_area_share, as: :float, label: false, input_html: {class: 'form-input-numeric'} %>
      </div>

      <div class="form-input-title">Asset manager</div>

      <%= f.fields_for :company do |loc| %>
        <%= loc.input :name, label: false %>
      <% end %>

app/views/business_assets/forms/_show_old.html.erb
<% content_for :navbar_links do %>
    <div class= "navbar-taz-left">
    <%= link_to "Edit", edit_business_asset_path, class: "navbar-taz-item navbar-taz-link navbar-title " %>
    <%= link_to "Compare", compare_path(@business_asset.last_transaction), class: "navbar-taz-item navbar-taz-link navbar-title " %>
    <p data-toggle="modal" data-target="#delete-modal" class="navbar-taz-item navbar-taz-link navbar-title">Delete</p>
     </div>
<% end %>
<%= render "modal" %>

<div class= "container" >
  <div class="row">
    <div class="col-xs-12 col-sm-6">
      <div class= "white-box height-line-1" >
        <h3> Descriptif </h3>
        <div class="descriptif">
            <div class="row">
              <div class="col-xs-4">
                <p><strong> Address :</strong></p>
              </div>
              <div class="col-xs-8 text-left">
                <p><%= @business_asset.geographical_location.address %></p>
              </div>
            </div>
            <% if  @business_asset.construction_year%>
              <div class="row">
                <div class="col-xs-4">
                  <p><strong> Construction Year :</strong></p>
                </div>
                <div class="col-xs-8 text-left">
                  <p><%= @business_asset.construction_year %></p>
                </div>
              </div>
            <% end %>
            <% if @business_asset.asset_type %>
              <div class="row">
                <div class="col-xs-4">
                  <p><strong> Asset Type :</strong></p>
                </div>
                <div class="col-xs-8 text-left">
                  <p><%= @business_asset.asset_type %></p>
                </div>
              </div>
            <% end %>
            <% if @business_asset.surface %>
              <div class="row">
                <div class="col-xs-4">
                  <p><strong> Surface :</strong></p>
                </div>
                <div class="col-xs-8 text-left">
                  <p><%= @business_asset.surface.round %> m²</p>
                </div>
              </div>
            <% end %>
            <% if @business_asset.general_condition %>
              <div class="row">
                <div class="col-xs-4">
                  <p><strong> General Condition :</strong></p>
                </div>
                <div class="col-xs-8 text-left">
                  <p><%= @business_asset.general_condition %></p>
                </div>
              </div>
            <% end %>
            <% if @business_asset.land_surface %>
              <div class="row">
                <div class="col-xs-4">
                  <p><strong> Land Surface :</strong></p>
                </div>
                <div class="col-xs-8 text-left">
                  <p><%= @business_asset.land_surface.round %> m²</p>
                </div>
              </div>
            <% end %>
            <% if @business_asset.description %>
              <div class="row">
                <div class="col-xs-4">
                  <p><strong> Description :</strong></p>
                </div>
                <div class="col-xs-8 text-left">
                  <p><%= @business_asset.description %></p>
                </div>
              </div>
            <% end %>
            <% if @business_asset.height %>
              <div class="row">
                <div class="col-xs-4">
                  <p><strong> Height :</strong></p>
                </div>
                <div class="col-xs-8 text-left">
                  <p><%= @business_asset.height %>m</p>
                </div>
              </div>
            <% end %>
            <% if @business_asset.office_area_share %>
              <div class="row">
                <div class="col-xs-4">
                  <p><strong> Office Area Share : </strong></p>
                </div>
                <div class="col-xs-8 text-left">
                  <p><%= @business_asset.office_area_share.round %>%</p>
                </div>
              </div>
            <% end %>
            <% if @business_asset.occupancy_rate %>
              <div class="row">
                <div class="col-xs-4">
                  <p><strong> Occupancy Rate : </strong></p>
                </div>
                <div class="col-xs-8 text-left">
                  <p><%= @business_asset.occupancy_rate.round %>%</p>
                </div>
              </div>
            <% end %>
            <% if @business_asset.transactions.last.price %>
              <div class="row">
               <div class="col-xs-4">
                  <p><strong> Price : </strong></p>
                </div>
                <div class="col-xs-8 text-left">
                  <p><%= format_number(@business_asset.transactions.last.price) %></p>
                </div>
              </div>
            <% end %>
            <% if @business_asset.rentals.last.annual_rent %>
              <div class="row">
               <div class="col-xs-4">
                  <p><strong> Annual Rent : </strong></p>
                </div>
                <div class="col-xs-8 text-left">
                  <p><%= format_number(@business_asset.rentals.last.annual_rent) %></p>
                </div>
              </div>
            <% end %>
            <% if @business_asset.has_icpe %>
              <div class="row">
                <div class="col-xs-4">
                  <p><strong>
                    <% if @business_asset.has_icpe %>
                      <i class="far fa-check-square"></i> <strong>    ICPE</strong>
                    <% else %>
                      <i class="far fa-square"></i> <strong>    ICPE</strong>
                    <% end %> </strong></p>
                </div>
              </div>
            <% end %>
          </div>
        </div>
      </div>

      <div class="col-xs-12 col-sm-6">
        <div class= "white-box height-line-1" >
        <div id="carousel-example-generic" class="carousel slide" data-ride="carousel">
          <!-- Indicators -->
          <ol class="carousel-indicators">
            <% @carroussel.each_with_index do |att, index| %>
              <% if index == 0  %>
                <li data-target="#carousel-example-generic" data-slide-to="0" class="active"></li>
              <% else %>
                <li data-target="#carousel-example-generic" data-slide-to="<% index %>""></li>
              <% end %>
            <% end %>
          </ol>

          <!-- Wrapper for slides -->
          <div class="carousel-inner" role="listbox">
            <% @carroussel.each_with_index do |att, index| %>
              <% if index == 0  %>
                <div class="item active">
                  <%= cl_image_tag att.file, crop: :fit, :format => :png %>
                </div>
              <% else %>
                <div class="item">
                  <%= cl_image_tag att.file, crop: :fit, :format => :png %>
                </div>
              <% end %>
            <% end %>
          </div>

          <!-- Controls -->
          <a class="left carousel-control" href="#carousel-example-generic" role="button" data-slide="prev">
            <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
            <span class="sr-only">Previous</span>
          </a>
          <a class="right carousel-control" href="#carousel-example-generic" role="button" data-slide="next">
            <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
            <span class="sr-only">Next</span>
          </a>
        </div>

      </div>
    </div>



    <div class="col-xs-12 col-sm-12">
      <div class= "white-box" >
        <h3> Localisation </h3>
        <div
          id="map"
          data-markers="<%= @markers.to_json %>"
          style="height: 400px"
        ></div>
      </div>
    </div>


     <div class="col-xs-12 col-sm-12">
      <div class= "white-box" >
        <h3> Rentals </h3>
         <table>
          <% @business_asset.rentals.each do |r| %>
            <tr>
              <th>Tenant</th>
              <th>Rent(y)</th>
              <th>Rent(y)/m2</th>
              <th>Entry</th>
              <th>Brk 1</th>
              <th>Brk 2</th>
              <th>Brk 3</th>
            </tr>
            <tr>

              <td><%= r.tenant.nil? ? '-' : r.tenant.name %></td>
              <td><%= format_number(r.annual_rent) %></td>
              <td><%= format_number(r.annual_rent_sqm) %></td>
              <td><%= r.start_date.nil? ? "-" : r.start_date.strftime('%b-%y') %> </td>
              <td><%= r.break_date_1.nil? ? "-" : r.break_date_1.strftime('%b-%y') %> </td>
              <td><%= r.break_date_2.nil? ? "-" : r.break_date_1.strftime('%b-%y') %> </td>
              <td><%= r.break_date_3.nil? ? "-" : r.break_date_1.strftime('%b-%y') %> </td>
            </tr>
          <% end %>
        </table>
      </div>
    </div>

    <div class="col-xs-12 col-sm-6 ">
      <div class="white-box">
        <h3> Last Transactions </h3>
        <table>
          <% @business_asset.transactions.each do |t| %>
            <tr>
              <th>Buyer</th>
              <th>Seller</th>
              <th>Date</th>
              <th>Price (M€)</th>
            </tr>
            <tr>
              <td><%= t.buyer.nil? ? '-' : t.buyer.name %></td>
              <td><%= t.seller.nil? ? '-' : t.seller.name %></td>
              <td><%= t.date.nil? ? "-" : t.date.strftime('%b-%y') %> </td>
              <td><%= format_number(t.price) %></td>
            </tr>
          <% end %>
        </table>
      </div>
    </div>

    <div class="col-xs-12 col-sm-6">
      <div class= "white-box" >
        <h3> Data-room </h3>
        <ul class="list-inline doc-attachment">
          <% @carroussel.each do |a| %>
             <li>
                <%= link_to a.file_url, target: :_blank do %>
                  <%= image_tag "file.svg" %>
                <% end %>
              </li>
          <% end %>
        </ul>
      </div>
    </div>


   </div>
</div>