config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'

  resources :business_assets do
    collection do
      get 'search/', :action => 'search', :as => 'search'
    end
  end

  get 'dashboard', to: "business_assets#dashboard", as: :dashboard
  get '/transactions/:id/compare', to: 'transactions#compare', as: 'compare'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/shared/_card.html.erb
<%= link_to business_asset_path(business_asset), class:"cards-links" do %>
  <div class="card2">
    <div class="card2-image" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.2)), url(<%= cl_image_path business_asset.attachments.where(attachment_type: 'photo').first.file%>);">
        <% if business_asset.asset_type == "Housing" %>
          <% card_color=  "#167AB2"  %>
        <% elsif business_asset.asset_type == "Office" %>
          <% card_color=  "#a43a2C"  %>
        <% elsif business_asset.asset_type == "Light Industrial" %>
          <% card_color=  "#4B6A69"  %>
        <% elsif business_asset.asset_type == "Retail" %>
          <% card_color=  "#F7C259"  %>
        <% else %>
          <% card_color=  "#a43a2C"  %>
        <% end %>
      <div class="card2-asset-type" style= "background-color: <%= card_color  %>;">
        <%= business_asset.asset_type %>
      </div>
      <div class="price">
      <% unless business_asset.transactions.empty? %>
        <h2><%= format_number(business_asset.transactions.first.price) %></h2>
      <% end %>
      </div>
    </div>
    <div class="card2-info">
      <div class="card2-info-address">
        <% if business_asset.geographical_location.address %>
          <h2><%= business_asset.geographical_location.address %></h2>
        <% else %>
          <p>No address</p>
        <% end %>
      </div>
      <div class="card2-other-info">
        <div class="surface-yield">
          <div class="card-surface">
            <p>Surface</p>
            <% if business_asset.surface %>
              <h2><%= format_number(business_asset.surface, currency_symbol: false) %>m²</h2>
            <% else %>
              <p>No surface</p>
            <% end %>
          </div>
          <div class="card-surface">
            <p> Yield</p>
            <% business_asset.rentals.each do |r| %>
              <% unless business_asset.transactions.empty? %>
                <% if r.annual_rent != 0 && business_asset.transactions.first.price != 0 %>
                  <h2><%= ((r.annual_rent / business_asset.transactions.first.price) * 100).round(2) %>%</h2>
                <% end %>
              <% end %>
            <% end %>
          </div>
        </div>
    </div>
  </div>
</div>
<% end %>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer">
  <div class="footer-links">
    All rights reserved - Designed at le Wagon - by geniuses
    <a href="https://www.braxtonam.com/"><i></i></a>
  </div>
</div>

app/views/shared/_navbar-medium.html.erb
  <div class="virtual div" style="height: 70px; width: 100%"></div>
  <div class="navbar-taz-medium navbar-taz navbar-taz-green">
    <!-- Logo -->
    <%= link_to business_assets_path, class: "navbar-taz-brand" do %>
      <%= image_tag "logo.svg", height: 70 %>
    <% end %>


    <div class="navbar-taz-right hidden-xs hidden-sm">


      <!-- Links -->
      <% if user_signed_in? %>
        <div class="navbar-taz-item-new">
          <div class="dropdown">

            <button class="hamburger hamburger--spin dropdown-toggle" type="button" data-toggle="dropdown">
              <span class="hamburger-box">
                <span class="hamburger-inner"></span>
              </span>
            </button>



            <ul class="dropdown-menu dropdown-menu-right navbar-taz-dropdown-menu">
              <li>
                <%= link_to business_assets_path, class: "navbar-taz-item navbar-taz-link" do %>
                  <i class="fa fa-user"></i> Profile
                <% end %>
              </li>
              <li>
                <%= link_to dashboard_path, class: "navbar-taz-item navbar-taz-link" do %>
                  <i class="fas fa-tachometer-alt"></i> Dashboard
                <% end %>
              </li>
              <li>
                <%= link_to new_business_asset_path, class: "navbar-taz-item navbar-taz-link" do %>
                  <i class="far fa-building"></i> Add asset
                <% end %>
              </li>
              <li>
                <%= link_to destroy_user_session_path, method: :delete, class: "navbar-taz-item navbar-taz-link" do %>
                  <i class="fas fa-hand-peace"></i>  <%= t(".sign_out", default: "Log out") %>
                <% end %>
              </li>
            </ul>
          </div>
        </div>
      <% else %>
        <%= link_to t(".sign_in", default: "Login"), new_user_session_path, class: "navbar-taz-item navbar-taz-link navbar-title" %>
      <% end %>
    </div>
  </div>

app/views/shared/_navbar-short.html.erb
  <div class="virtual div" style="height: 70px; width: 100%"></div>
  <div class="navbar-taz-short navbar-taz navbar-taz-green">
    <!-- Logo -->
    <%= link_to business_assets_path, class: "navbar-taz-brand" do %>
      <%= image_tag "logo.svg", height: 70 %>
    <% end %>


    <div class="navbar-taz-right hidden-xs hidden-sm">


      <!-- Links -->
      <% if user_signed_in? %>
        <div class="navbar-taz-item-new">
          <div class="dropdown">

            <button class="hamburger hamburger--spin dropdown-toggle" type="button" data-toggle="dropdown">
              <span class="hamburger-box">
                <span class="hamburger-inner"></span>
              </span>
            </button>



            <ul class="dropdown-menu dropdown-menu-right navbar-taz-dropdown-menu">
              <li>
                <%= link_to business_assets_path, class: "navbar-taz-item navbar-taz-link" do %>
                  <i class="fa fa-user"></i> Profile
                <% end %>
              </li>
              <li>
                <%= link_to dashboard_path, class: "navbar-taz-item navbar-taz-link" do %>
                  <i class="fas fa-tachometer-alt"></i> Dashboard
                <% end %>
              </li>
              <li>
                <%= link_to new_business_asset_path, class: "navbar-taz-item navbar-taz-link" do %>
                  <i class="far fa-building"></i> Add asset
                <% end %>
              </li>
              <li>
                <%= link_to destroy_user_session_path, method: :delete, class: "navbar-taz-item navbar-taz-link" do %>
                  <i class="fas fa-hand-peace"></i>  <%= t(".sign_out", default: "Log out") %>
                <% end %>
              </li>
            </ul>
          </div>
        </div>
      <% else %>
        <%= link_to t(".sign_in", default: "Login"), new_user_session_path, class: "navbar-taz-item navbar-taz-link navbar-title" %>
      <% end %>
    </div>
  </div>

app/views/shared/_navbar.html.erb
<div class="virtual div" style="height: 70px; width: 100%"></div>
<div class="navbar-taz navbar-fixed-top navbar-taz-white">
  <!-- Logo -->
  <%= link_to business_assets_path, class: "navbar-taz-brand" do %>
    <%= image_tag "logo.svg", height: 50 %>
  <% end %>

  <!-- Left Navigation in asset show -->
  <%= yield :navbar_links %>

  <!-- Right Navigation -->
  <div class="navbar-taz-right hidden-xs hidden-sm">

    <!-- Links -->
    <%= link_to "Home", business_assets_path, class: "navbar-taz-item navbar-taz-link navbar-title" %>
    <%= link_to "Add Asset", new_business_asset_path, class: "navbar-taz-item navbar-taz-link navbar-title" %>
    <%= link_to "Dashboard", dashboard_path, class: "navbar-taz-item navbar-taz-link navbar-title" %>
    <% if user_signed_in? %>
      <div class="navbar-taz-item">
        <div class="dropdown">
          <%= image_tag "admin_avatar.png", class: "main-avatar dropdown-toggle", id: "navbar-taz-menu", "data-toggle" => "dropdown", title: current_user.email %>
          <ul class="dropdown-menu dropdown-menu-right navbar-taz-dropdown-menu">
            <li>
              <%= link_to business_assets_path do %>
                <i class="fa fa-user"></i> Profile
              <% end %>
            </li>
            <li>
              <%= link_to "#" do %>
                <i class="fa fa-cog"></i>  <%= t(".settings", default: "Settings") %>
              <% end %>
            </li>
            <li>
              <%= link_to destroy_user_session_path, method: :delete do %>
                <i class="fa fa-sign-out"></i>  <%= t(".sign_out", default: "Log out") %>
              <% end %>
            </li>
          </ul>
        </div>
      </div>
    <% else %>
      <%= link_to t(".sign_in", default: "Login"), new_user_session_path, class: "navbar-taz-item navbar-taz-link navbar-title" %>
    <% end %>
  </div>
</div>

app/views/shared/_search_menu.html.erb
<%= form_tag search_business_assets_path, method: :get, remote: true do %>
  <%= text_field_tag :query,params[:query]%>
  <%= submit_tag 'Search' %>
<% end %>